### ISSUE TITLE
Было бы здорово вывести массив Контролов карты

### ISSUE THREAD

**Issue by sagrael** [just-boris/angular-ymaps#10]
https://tech.yandex.ru/maps/doc/jsapi/2.0/ref/reference/map.control.Manager-docpage/
чтобы например убрать searchControl при инициализации

**Comment by just-boris** [comment]
не нашел возможности указать в API список контролов.
Написал по этому поводу вопрос разработчикам: http://clubs.ya.ru/mapsapi/replies.xml?item_no=57804

**Comment by sagrael** [comment]
Спасибо) было бы здорово их настраивать как mapBehaviors

**Comment by belkaaa** [comment]
В https://tech.yandex.ru/maps/doc/jsapi/2.1/ref/reference/Map-docpage/ state.controls

**Comment by just-boris** [comment]
Update: можно передавать контролы как параметры.
Pull-requests welcome! Посмотрев, как сделаны behaviors, можно сделать это очень легко

**Comment by just-boris** [comment]
Released as v0.1.1
