### ISSUE TITLE
Было бы удобно сделать несколько карт на странице

### ISSUE THREAD

**Issue by shcoderAlex** [just-boris/angular-ymaps#11]

**Comment by just-boris** [comment]
Теоретически, сейчас несколько карт должны работать.
Расскажите, что именно у вас не работает

**Comment by shcoderAlex** [comment]
Добрый

20 июля 2015 г., 18:52 пользователь Boris Serdiuk <notifications@github.com>
написал:

**Comment by just-boris** [comment]
Скорее всего дело в том, что обе ваши карты ссылаются на одни и те же свойства center и zoom в атрибутах.
Я добавил страницу с двумя картами в примеры http://catatron.com/angular-ymaps/examples/multi-map/

У одной карты свойства сохраняются в объект `leftMap`

```html
<yandex-map center="leftMap.center" zoom="leftMap.zoom"></yandex-map>
```
А у второй – `rightMap`

```html
<yandex-map center="rightMap.center" zoom="rightMap.zoom"></yandex-map>
```

А если сохранять в общий объект, то они будут синхронизироваться. Возможно, это даже полезная фича

**Comment by just-boris** [comment]
Пример добавил в документацию, считаю задачу закрытой
