### ISSUE TITLE
Не работает опция zoom

### ISSUE THREAD

**Issue by vlaad360** [just-boris/angular-ymaps#12]
При загрузке страницы происходит инициализация карты, на секунду она имеет правильный масштаб, но потом скидывает масштаб в рамках всей Москвы

```html
<div ng-init="coords=[55.77,37.64];center=[55.77,37.64];zoom=17">
    <yandex-map center="center" zoom="zoom">
         <ymap-marker coordinates="coords"></ymap-marker>
    </yandex-map>
</div>
```

С модулем все нормально, добавлен в зависимости

**Comment by goooseman** [comment]
+1 Точно такое же поведение. Если не добавлять маркер - масштаб устанавливается правильно

**Comment by goooseman** [comment]
Все просто:
``` coffeescript
app.config (ymapsConfig) ->
  ymapsConfig.fitMarkers = false
```

**Comment by just-boris** [comment]
Хм, да. Опция `fitMarkers` для того и задумана, чтобы отображать маркеры в лучшем виде.
Если ее отключить, то можно управлять центром и масштабом карты как вам удобнее

**Comment by goooseman** [comment]
@just-boris вот только выходит так, что для одного единственного маркера он устанавливает zoom - 8 (примерно). а он прекрасно влазит, даже если zoom - 15.

**Comment by just-boris** [comment]
[Немного поправил](https://github.com/just-boris/angular-ymaps/commit/c8433146f59d35af9003c4bb34e92106a9684b0d), чтобы уставливал zoom=15 вместо 8.

Это происходило из-за того, что библиотека имитировала опцию [zoomMargin](https://tech.yandex.ru/maps/doc/jsapi/2.1/ref/reference/Map-docpage/#setBounds-param-options.zoomMargin) из API Карт. Имитация была неполной и ломалась на больших zoom. 
Сейчас опция есть, и код по имитации я удалил

**Comment by just-boris** [comment]
Я не сделал новый релиз, потому что пока не уверен, что всем пользователям понравится, что [в этом примере](http://catatron.com/angular-ymaps/examples/color-marker/) теперь будет перекресток крупным планом.

**Comment by goooseman** [comment]
@just-boris мне кажется, логика должна быть другой.
Сначала показывается карта с тем zoom, который установил пользователь. Если все точки поместились - ничего не делаем, если нет, то устанавливаем тот максимальный zoom, при котором все точки видны.

**Comment by just-boris** [comment]
Хм, то есть для `autoFit` только уменьшаем zoom, но никак не увеличиваем? Можно попробовать. 

Мне сейчас не хватает времени на это, если хотите получить результат быстрее, можете сами поколдовать вокруг [этого метода](https://github.com/just-boris/angular-ymaps/blob/master/angular-ymaps.js#L93) и прислать pull-request

**Comment by goooseman** [comment]
Прошу :)
