### ISSUE TITLE
Объединение маркеров в кластеры

### ISSUE THREAD

**Issue by ArqinT** [just-boris/angular-ymaps#14]
Возможно ли при использовании вашей бибилиотеки объединять маркеры в кластеры?

**Comment by just-boris** [comment]
Нет, пока это никак не сделать. Но вещь хорошая, пора бы запилить. Такое API вас устроит?

```
angular.module('MyApp', ['ymaps']).config(function(ymapsConfig) {
    //по умолчанию false
    ymapsConfig.clusterize = true;
});
```

**Comment by ArqinT** [comment]
Да, вполне. 
Еще бы до кучи и управление контролами прикрутить :+1:

**Comment by ArqinT** [comment]
Тоже что-то типа:
```javascript
angular.module('MyApp', ['ymaps']).config(function(ymapsConfig) {
    //по умолчанию false
    ymapsConfig.controls = [fullscreenControl, zoomControl];
});
```

**Comment by just-boris** [comment]
Кластеризация готова: http://catatron.com/angular-ymaps/examples/clusterize/
Опубликовал версию `0.1.0`
