### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by umed48** [just-boris/angular-ymaps#19]
Планируется поддержка нового ангуляра?

**Comment by just-boris** [comment]
Если поддержка потребует небольших правок в коде, можно сделать.

Но насколько я понимаю, там значительные изменения component API, в частности наш способ загрузки маркеров на карту не заработает совсем. Поэтому, скорее всего, нужно делать новый модуль.

**Comment by umed48** [comment]
@just-boris , скорее всего, новый модуль. Ну ладно, спасибо за ответ))
