### ISSUE TITLE
Все работает, но не отображаются внутрености Яндекс Карты (аттачмент)

### ISSUE THREAD

**Issue by skobak** [just-boris/angular-ymaps#20]
Добрый день!

![gt](https://cloud.githubusercontent.com/assets/6191306/14539405/f5c378b0-0288-11e6-9ac1-80870861a69d.png)

Код из примера:

js:
```
app.controller('MapCtrl', function($scope) {
    //создаем массив координат. При желании его можно загружать и с сервера,
    //подробнее об этом - в документации Angular
    $scope.markers = [
        [54.46, 38.31],
        [53.57, 37.13],
        [53.14, 37.59]
    ];
    //настройки положения карты
    $scope.map = {
        center: [53.57, 37.13], zoom: 12
    };
});
```

html:
```
<div ng-controller="MapCtrl">
        <yandex-map center="map.center" zoom="map.zoom">
            <ymap-marker ng-repeat="marker in markers" index="$index+1" coordinates="marker"></ymap-marker>
        </yandex-map>
    </div>
```

css:
```
yandex-map {
  display: block;
  width: 100%;
  height: 400px;
}

```
Ошибок в консоли хрома нету, все грузится нормально, даже куски карт яндекса, но не показываются почему-то?

Браузер не самый свежий, но ваши примеры у вас на сайте работают корректно

**Comment by skobak** [comment]
Проблема была в стилях,  так как сайт использует sb-admin-2 (надстройка над bootstrap), а в ней стили:
'''
canvas {
            max-width: 100% !important;
            max-width: 400px;
            height: auto !important;
}
''''

Добавление этого стиля, исправило положение
'''
ymaps canvas {
  max-width: none!important;
  max-height: none!important;
}
'''

Всем удачи!

**Comment by just-boris** [comment]
Спасибо информацию! Может, кому-то пригодится
